language: java
jdk:
- oraclejdk8
deploy:
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: martin.schmollinger@reutlingen-university.de
  password:    
    secure: OUA8v758BK+hJgnASuMhEehZBdfmKC8ZxXvBcvK3XvqCYzmFes+SpUmZ03duWCYn0MZjpMTjkfz+/VZYitj4+AOES1InDBviiJOvZVwuG9TcYKuJdATNO+iZGjLcc+QRa4RxLgD0UkL1REn1rpoy3N/HsD2kYEO7Rcuk/jFTzieEvkvhK62Fe7/fYd0emRM7V5D6hVNwD2e8zbPLnB7CN6rXtqpt1B1fVl5oOe7eT9BcDKiCkhGnGLBSp8Zu5A7X88lxV8Q/+ExtBp3sR39W6V/GsNE/SRfOHyDP62fkRuAVCorTlo74HAgrnpGmGP/vtyy9o2nMHQ/tj37UmSl5IMlxCr4ZXqcgv3p9mieQ6pRzKR23KW0cRdj6u4QZvj+p0AvVgjcRK+d1H4lkcc4KN3/QV8YjLkb5wqHCPgY/Nb2bOZWDdzl5N970v6MYR+VHrvfk7VJgI/qqLdxcqOubv+EWoarjM2sNNsPX6mNqluvxvYqbL3KSXKOgNn149EkdvnexuDiSoBeWSczOn0rAdxB6qZOjG9XuwYt0s8gVG5M0tdz32EbxtYhk7NZs1/ep2HDjc8s0Vy3B7BWqLn8uKNEIbo1NJgikwoQAcsHeoOGgSrZGQmvOs3XKKywKd7cy6MNV5XsEyaLL6ln5oFTT8xuxLQ0Z/CReypohNvcZhAk=
  organization: EduCaMa
  space: dev
  on:
    repo: schmolli1/Showcase
