language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x *.sh
before_script:
  - source ./start-xvfb.sh
script: 
  # Overwrite default "./mvnw test" so that the integration tests are executed as well.
  - ./mvnw verify
after_success:
- ./upload-serenity-reports.sh
deploy:
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: martin.schmollinger@reutlingen-university.de
  password:
    secure: NLL72dJYAxLi3y20fRANNXT+PokTkk7M7+/LywRSKtgm5E1s0h7Y/2PTa51FHY7S0diZzfJubZ6pitOxnR2USUZnRBY0CGPp5kDYLRLWli8AM9gkqth4dD/CiDifsQrCzt0YgKR8uDGKhSSN3SfYbVBABTs1+kSMUNRqzAD69O7EmkSKpXl4jOWIimXTWA32YJUwV6+oDvx5cuvHKsMIJ/OQPLlr6K257gq7VDQ2r48VOko3EbFMaJod9w9OTnX1SaYvnXJVZXsH9meMzEz+oDywAx7OcqHKH8F5r8Xd1jooQkAyfOqvZ9AEf3qT9kTssKq9Wfuxn8qufyHMJXM2fXsFthl/0RZxtw8JFGbbYQNpFAE9rse5ogmgX8MoKqshOpVNQcm38soXIklPsy8EyrrG5L5q+iC0pXpXzh7mg0apJx7OGhqW1UOgioz//xcsnIbfsQm/Eqq2MiYxsoa/xYJfVWlCYBcmKJSGDpQ/7SD2XBMgOJ+ukymknOUQSNMtocDA9M1SAkWsjPktRcijOXPj1fz9zp0cTh9pZkNyRyxyRXf/8MHZ2EkaBTYjJOE5hgkzNbgDTvDMy9GOzaMFqgVGtqdXrhLwi0dsCX/GNS+UwvBJIdwGRMoK1uvOiq8UlFvj84Yu6cusOjbuRQdIHe2BTCkR/tC3UFMM473MkfQ=
  organization: EduCaMa
  space: dev
  on:
    repo: schmolli1/Showcase
addons:
  firefox: "42.0"
