language: java
jdk:
- oraclejdk8
deploy:
  provider: cloudfoundry
  api: https://api.ng.bluemix.net
  username: martin.schmollinger@reutlingen-university.de
  password:
    secure: Mm0lo5FQotDjc2dZO2tIBUkRyUxVcoBA4iYpnw3F0CCj5Ff4caYuOcgxHbOpzYEvT2gmnE+HkgzywztyM9xNj7+/j7e9KOrqru+JBh9lClJwhCIQHC7HyezNcso9MH6iirOeilT6qo2du3eyaNKQimDwRaYSYLx491vjtsTZf7hUs8BC7FuipoZamX1TB3Rn1vdEICVlk93DwZa/+lYgadW10XXbF6I1Ypzemqyh4l1jy99ReX0+QWb1/GZ6U8ZnnYETNh0s2YvX04ErHkKEBhA14h4V9Le87NSb8MWH4CSha99GoVxc+ao59TSxxT7yBWr73MRLseNIst7UnTR/JPX2hWpCUKlIfmr1WbKu1XBuw6zRK8SC3LwDbCNsKQLh1XDDwWDRxcP/Re+atnEKCONCKMVvz9EmN7dw5rfv+IcK0X19LRuto+TXByJpdBQlXW1er7TILP/2zV3zpKrnBwJ6YOPBBpHRYMy+k8gk8YD54Nzc9eB4vEdbub9s8SYGO9GM6OmRI6QEIEF8ZUEy6oLCYDgXpG6y0VgO0Ms6tHZnybMbq/IybqjhJsgQyv/aEhzNVBr2eQtqG6pesJF/xOyAAPl9R8Zir/qlFwwyvI9uTpEpxRCwuHrT7Lj0kKDVhO9xcE1w2fohWR6qB20nIEVHqSuEr3n5bZr9cKBqrrE=
  organization: EduCaMa
  space: dev
  on:
    repo: schmolli1/Showcase
